services:
  - type: web
    name: zona3b-rastreo-server
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://zona3brandon.us,https://www.zona3brandon.us
      - key: TRACK17_API_KEY
        sync: false
